# FinRAD — Financial Readability Assessment Dataset

[FinRAD dataset](https://huggingface.co/datasets/sohomghosh/FinRAD_Financial_Readability_Assessment_Dataset) dataset from Hugging Face (13k+ definitions of financial terms with readability labels)

In [1]:
from datasets import load_dataset
import pandas as pd

## Load dataset

In [3]:
finrad = load_dataset("sohomghosh/FinRAD_Financial_Readability_Assessment_Dataset")
finrad

DatasetDict({
    train: Dataset({
        features: ['terms', 'definitions', 'source', 'assigned_readability', 'flesch_reading_ease', 'flesch_kincaid_grade', 'smog_index', 'coleman_liau_index', 'automated_readability_index', 'dale_chall_readability_score', 'linsear_write_formula', 'gunning_fog'],
        num_rows: 13112
    })
})

## Train split

In [4]:
train = finrad["train"]
print(f"Rows: {len(train)}")
print(f"Columns: {train.column_names}")
train

Rows: 13112
Columns: ['terms', 'definitions', 'source', 'assigned_readability', 'flesch_reading_ease', 'flesch_kincaid_grade', 'smog_index', 'coleman_liau_index', 'automated_readability_index', 'dale_chall_readability_score', 'linsear_write_formula', 'gunning_fog']

Dataset({
    features: ['terms', 'definitions', 'source', 'assigned_readability', 'flesch_reading_ease', 'flesch_kincaid_grade', 'smog_index', 'coleman_liau_index', 'automated_readability_index', 'dale_chall_readability_score', 'linsear_write_formula', 'gunning_fog'],
    num_rows: 13112
})

## Train data

In [5]:
df = train.to_pandas()
print(df.shape)
df.head(10)

(13112, 12)

,terms,definitions,source,assigned_readability,flesch_reading_ease,flesch_kincaid_grade,smog_index,coleman_liau_index,automated_readability_index,dale_chall_readability_score,linsear_write_formula,gunning_fog
0,adjusted present value (apv),net present value of an asset if financed sole...,prin,0,59.64,9.9,0.0,9.40,10.5,10.16,12.0,12.00
1,agency costs,"costs that arise when an agent (e.g., a manage...",prin,0,66.07,9.5,0.0,7.78,12.3,10.47,15.0,14.25
2,annual percentage rate (apr),"the interest rate per period (e.g., per month)...",prin,0,62.68,8.7,0.0,6.67,8.4,10.98,12.5,16.21
3,annuity,investment that produces a level stream of cas...,prin,0,56.25,9.1,0.0,9.56,8.7,9.64,10.5,14.00
4,annuity due,annuity whose payments occur at the start of e...,prin,0,61.33,7.2,0.0,8.50,6.2,10.45,6.0,12.00
5,annuity factor,present value of $1 paid for each of t periods.,prin,0,86.71,3.7,0.0,2.12,1.5,8.87,5.0,8.00
6,apr,annual percentage rate.,prin,0,9.21,12.7,0.0,13.12,13.0,14.31,2.5,27.87
7,apt,arbitrage pricing theory.,prin,0,-24.64,17.4,0.0,16.95,16.2,19.58,2.5,27.87
8,apv,adjusted present value.,prin,0,34.59,9.2,0.0,13.12,13.0,9.05,1.5,14.53
9,arbitrage,purchase of one security and simultaneous sale...,prin,0,27.49,18.1,0.0,11.50,19.9,11.24,24.5,20.86

## Main columns

- **terms**: financial term
- **definitions**: definition text
- **source**: source of the term (e.g. prin, investopedia)
- **assigned_readability**: 0 = not readable, 1 = readable
- Other columns: readability scores (flesch_reading_ease, flesch_kincaid_grade, etc.)

In [6]:
df[["terms", "definitions", "source", "assigned_readability"]].head(10)

,terms,definitions,source,assigned_readability
0,adjusted present value (apv),net present value of an asset if financed sole...,prin,0
1,agency costs,"costs that arise when an agent (e.g., a manage...",prin,0
2,annual percentage rate (apr),"the interest rate per period (e.g., per month)...",prin,0
3,annuity,investment that produces a level stream of cas...,prin,0
4,annuity due,annuity whose payments occur at the start of e...,prin,0
5,annuity factor,present value of $1 paid for each of t periods.,prin,0
6,apr,annual percentage rate.,prin,0
7,apt,arbitrage pricing theory.,prin,0
8,apv,adjusted present value.,prin,0
9,arbitrage,purchase of one security and simultaneous sale...,prin,0

## Label and source distribution

In [7]:
print("assigned_readability value counts:")
print(df["assigned_readability"].value_counts().sort_index())
print()
print("source value counts:")
print(df["source"].value_counts())

assigned_readability value counts:
assigned_readability
0    5508
1    7604
Name: count, dtype: int64

source value counts:
source
investopedia          5946
palgrave              3925
opod                   527
zvi                    492
economist              457
fmi                    387
6_8_louis              342
sam                    331
9_12_louis             188
prin                   177
ncert                  115
ncert_keec111           95
ncert_kest              53
ncert_class12_econ      41
pre_louis               36
Name: count, dtype: int64

## Readability score columns (summary)

In [8]:
score_cols = [
    "flesch_reading_ease", "flesch_kincaid_grade", "smog_index",
    "coleman_liau_index", "automated_readability_index", "dale_chall_readability_score",
    "linsear_write_formula", "gunning_fog"
]
df[score_cols].describe()

,flesch_reading_ease,flesch_kincaid_grade,smog_index,coleman_liau_index,automated_readability_index,dale_chall_readability_score,linsear_write_formula,gunning_fog
count,13112.000000,13112.000000,13112.000000,13112.000000,13112.000000,13112.000000,13112.000000,13112.000000
mean,42.304360,12.264628,4.379042,12.057892,13.668830,10.608385,13.139519,14.414410
std,23.705007,4.440433,6.596280,4.281754,5.278037,2.148938,6.617198,5.107517
min,-301.790000,-3.500000,0.000000,-33.810000,-6.900000,0.100000,-0.500000,0.400000
25%,30.870000,9.700000,0.000000,9.880000,10.500000,9.380000,8.666667,11.600000
50%,43.390000,12.300000,0.000000,12.020000,13.500000,10.460000,13.250000,14.330000
75%,55.920000,14.600000,12.000000,14.340000,16.500000,11.640000,16.750000,17.130000
max,121.220000,55.600000,26.500000,51.360000,65.000000,35.270000,73.000000,56.000000

In [9]:
df[["terms", "definitions"]].head()

,terms,definitions
0,adjusted present value (apv),net present value of an asset if financed sole...
1,agency costs,"costs that arise when an agent (e.g., a manage..."
2,annual percentage rate (apr),"the interest rate per period (e.g., per month)..."
3,annuity,investment that produces a level stream of cas...
4,annuity due,annuity whose payments occur at the start of e...

In [10]:
df[["source"]].value_counts()

source
investopedia          5946
palgrave              3925
opod                   527
zvi                    492
economist              457
fmi                    387
6_8_louis              342
sam                    331
9_12_louis             188
prin                   177
ncert                  115
ncert_keec111           95
ncert_kest              53
ncert_class12_econ      41
pre_louis               36
Name: count, dtype: int64

In [11]:
df["definitions"].str.len().describe()

count    13112.000000
mean       259.639414
std        170.182080
min          3.000000
25%        127.000000
50%        251.000000
75%        366.000000
max       4200.000000
Name: definitions, dtype: float64

In [12]:
df["terms"].str.len().describe()

count    13112.000000
mean        16.917480
std          9.362979
min          1.000000
25%         11.000000
50%         15.000000
75%         21.000000
max        156.000000
Name: terms, dtype: float64

In [13]:
df["source"].str.len().describe()

count    13112.000000
mean         9.279362
std          3.081504
min          3.000000
25%          8.000000
50%          9.000000
75%         12.000000
max         18.000000
Name: source, dtype: float64